all:
	capnp compile -oc++ vector.capnp
	capnp compile -oc++ scene.capnp 
	capnp compile -oc++ entity.capnp 
	capnp compile -oc++ image.capnp 
	capnp compile -oc++ mesh.capnp 
	capnp compile -oc++ material.capnp 